"""add user 

Revision ID: f451f85c8d58
Revises: 9d2d188a442e
Create Date: 2025-10-23 10:11:28.119466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f451f85c8d58'
down_revision: Union[str, Sequence[str], None] = '9d2d188a442e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_time', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('updated_time', sa.DateTime(), nullable=True))
    op.alter_column('users', 'mobile_phone',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=11),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', mysql.DATETIME(), nullable=False))
    op.add_column('users', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.alter_column('users', 'mobile_phone',
               existing_type=sa.String(length=11),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('users', 'updated_time')
    op.drop_column('users', 'created_time')
    # ### end Alembic commands ###
